// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCCSZ4A7aGhuImb-dz1Y00-vofk_W7MI',
    appId: '1:777266326941:web:31312413d00285db03d374',
    messagingSenderId: '777266326941',
    projectId: 'mi-agenda-flutter-d4d7d',
    authDomain: 'mi-agenda-flutter-d4d7d.firebaseapp.com',
    storageBucket: 'mi-agenda-flutter-d4d7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jYF-Fr3mQ1f2L7SCgAm-4IaD6Gytcso',
    appId: '1:777266326941:android:03b4f193ebd8c8e703d374',
    messagingSenderId: '777266326941',
    projectId: 'mi-agenda-flutter-d4d7d',
    storageBucket: 'mi-agenda-flutter-d4d7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7KaTDTyUwCMnTHRI29oZ3i_S4EKNagw',
    appId: '1:777266326941:ios:06a503171eb3dd6203d374',
    messagingSenderId: '777266326941',
    projectId: 'mi-agenda-flutter-d4d7d',
    storageBucket: 'mi-agenda-flutter-d4d7d.firebasestorage.app',
    iosBundleId: 'com.example.miAgenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.miAgenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCCSZ4A7aGhuImb-dz1Y00-vofk_W7MI',
    appId: '1:777266326941:web:fb7a45d6b560cf1203d374',
    messagingSenderId: '777266326941',
    projectId: 'mi-agenda-flutter-d4d7d',
    authDomain: 'mi-agenda-flutter-d4d7d.firebaseapp.com',
    storageBucket: 'mi-agenda-flutter-d4d7d.firebasestorage.app',
  );

}